var testeA=[
{nome:"Felipe Gaspar", nomeU:"Felipe%20Gaspar", data:"01/01", pe:"D", foto:"FOTOS/FelipeGaspar.jpeg", ao:"o"},
{nome:"Pimenta", nomeU:"Pimenta", data:"03/01", pe:"A", foto:"FOTOS/Pimenta.jpeg", ao:"o"},
{nome:"Silveira", nomeU:"Silveira", data:"06/01", pe:"B", foto:"FOTOS/Silveira.jpeg", ao:"o"},
{nome:"Múrcia", nomeU:"Múrcia", data:"06/01", pe:"F", foto:"FOTOS/Murcia.jpeg", ao:"o"},
{nome:"Gadioli", nomeU:"Gadioli", data:"09/01", pe:"F", foto:"FOTOS/Gadioli.jpeg", ao:"o"},
{nome:"Isack", nomeU:"Isack", data:"10/01", pe:"D", foto:"FOTOS/Isack.jpeg", ao:"o"},
{nome:"Alberto", nomeU:"Alberto", data:"12/01", pe:"B", foto:"FOTOS/Alberto.jpeg", ao:"o"},
{nome:"R Silva", nomeU:"R%20Silva", data:"15/01", pe:"F", foto:"FOTOS/R.Silva.jpeg", ao:"o"},
{nome:"Freire", nomeU:"Freire", data:"20/01", pe:"D", foto:"FOTOS/Freire.jpeg", ao:"o"},
{nome:"Figueiredo", nomeU:"Figueiredo", data:"21/01", pe:"F", foto:"FOTOS/Figueiredo.jpeg", ao:"o"},
{nome:"J. Alves", nomeU:"J.%20Alves", data:"22/01", pe:"E", foto:"FOTOS/J.Alves.jpeg", ao:"o"},
{nome:"Fábio Nascimento", nomeU:"Fábio%20Nascimento", data:"24/01", pe:"E", foto:"FOTOS/FábioNascimento.jpeg", ao:"o"},
{nome:"Damazio", nomeU:"Damazio", data:"24/01", pe:"E", foto:"FOTOS/Damazio.jpeg", ao:"o"},
{nome:"Miranda", nomeU:"Miranda", data:"28/01", pe:"F", foto:"FOTOS/Miranda.jpeg", ao:"o"},
{nome:"João Paulo", nomeU:"João%20Paulo", data:"29/01", pe:"D", foto:"FOTOS/JoãoPaulo.jpeg", ao:"o"},
{nome:"Paulo Cezar", nomeU:"Paulo%20Cezar", data:"30/01", pe:"A", foto:"FOTOS/PauloCezar.jpeg", ao:"o"},
{nome:"Berbelini", nomeU:"Berbelini", data:"01/02", pe:"C", foto:"FOTOS/Berbelini.jpg", ao:"o"},
{nome:"Henrique Mascarenhas", nomeU:"Henrique%20Mascarenhas", data:"04/02", pe:"C", foto:"FOTOS/HenriqueMascarenhas.jpg", ao:"o"},
{nome:"Helena", nomeU:"Helena", data:"06/02", pe:"C", foto:"FOTOS/Helena.jpg", ao:"o"},
{nome:"Vertemati", nomeU:"Vertemati", data:"06/02", pe:"C", foto:"FOTOS/Vertemati.jpg", ao:"o"},
{nome:"Jonatan Vieira", nomeU:"Jonatan%20Vieira", data:"13/02", pe:"C", foto:"FOTOS/JonatanVieira.jpg", ao:"o"},
{nome:"Mardegam", nomeU:"Mardegam", data:"14/02", pe:"F", foto:"FOTOS/Mardegam.jpeg", ao:"o"},
{nome:"Peron", nomeU:"Peron", data:"16/02", pe:"A", foto:"FOTOS/Peron.jpeg", ao:"o"},
{nome:"Faustino", nomeU:"Faustino", data:"19/02", pe:"A", foto:"FOTOS/Faustino.jpeg", ao:"o"},
{nome:"Gian Luca", nomeU:"Gian%20Luca", data:"19/02", pe:"E", foto:"FOTOS/GianLuca.jpeg", ao:"o"},
{nome:"Abissi", nomeU:"Abissi", data:"21/02", pe:"C", foto:"FOTOS/Abissi.jpg", ao:"o"},
{nome:"Bruno Macedo", nomeU:"Bruno%20Macedo", data:"21/02", pe:"C", foto:"FOTOS/BrunoMacedo.jpg", ao:"o"},
{nome:"Bonifácio", nomeU:"Bonifácio", data:"21/02", pe:"F", foto:"FOTOS/Bonifácio.jpeg", ao:"o"},
{nome:"Ayumi", nomeU:"Ayumi", data:"23/02", pe:"B", foto:"FOTOS/Ayumi.jpeg", ao:"o"},
{nome:"Bryan Ribeiro", nomeU:"Bryan%20Ribeiro", data:"23/02", pe:"D", foto:"FOTOS/BryanRibeiro.jpeg", ao:"o"},
{nome:"Souza", nomeU:"Souza", data:"23/02", pe:"F", foto:"FOTOS/Souza.jpeg", ao:"o"},
{nome:"Juan Barros", nomeU:"Juan%20Barros", data:"27/02", pe:"A", foto:"FOTOS/JuanBarros.jpeg", ao:"o"},
{nome:"Noriler", nomeU:"Noriler", data:"27/02", pe:"F", foto:"FOTOS/Noriler.jpeg", ao:"o"},
{nome:"Reinhardt", nomeU:"Reinhardt", data:"28/02", pe:"C", foto:"FOTOS/Reinhardt.jpg", ao:"o"},
{nome:"Arthur Rocha", nomeU:"Arthur%20Rocha", data:"01/03", pe:"C", foto:"FOTOS/ArthurRocha.jpg", ao:"o"},
{nome:"Bertoco", nomeU:"Bertoco", data:"03/03", pe:"B", foto:"FOTOS/Bertoco.jpeg", ao:"o"},
{nome:"Silva", nomeU:"Silva", data:"03/03", pe:"B", foto:"FOTOS/Silva.jpeg", ao:"o"},
{nome:"Matheus Santana", nomeU:"Matheus%20Santana", data:"07/03", pe:"E", foto:"FOTOS/MatheusSantana.jpeg", ao:"o"},
{nome:"Gabriel Amaral", nomeU:"Gabriel%20Amaral", data:"09/03", pe:"F", foto:"FOTOS/GabrielAmaral.jpeg", ao:"o"},
{nome:"Magalhães", nomeU:"Magalhães", data:"11/03", pe:"B", foto:"FOTOS/Magalhães.jpeg", ao:"o"},
{nome:"Malacrida", nomeU:"Malacrida", data:"11/03", pe:"B", foto:"FOTOS/Malacrida.jpeg", ao:"o"},
{nome:"Rodrigues Silva", nomeU:"Rodrigues%20Silva", data:"15/03", pe:"F", foto:"FOTOS/RodriguesSilva.jpeg", ao:"o"},
{nome:"Alessandro", nomeU:"Alessandro", data:"24/03", pe:"A", foto:"FOTOS/Alessandro.jpeg", ao:"o"},
{nome:"Kalapachi", nomeU:"Kalapachi", data:"30/03", pe:"E", foto:"FOTOS/Kalapachi.jpeg", ao:"o"},
{nome:"Chaves", nomeU:"Chaves", data:"02/04", pe:"F", foto:"FOTOS/Chaves.jpeg", ao:"o"},
{nome:"Gabry", nomeU:"Gabry", data:"04/04", pe:"B", foto:"FOTOS/Gabry.jpeg", ao:"o"},
{nome:"Lisboa", nomeU:"Lisboa", data:"06/04", pe:"E", foto:"FOTOS/Lisboa.jpeg", ao:"o"},
{nome:"Dabague", nomeU:"Dabague", data:"11/04", pe:"D", foto:"FOTOS/Dabague.jpeg", ao:"o"},
{nome:"Valiante", nomeU:"Valiante", data:"11/04", pe:"D", foto:"FOTOS/Valiante.jpeg", ao:"o"},
{nome:"Custódio", nomeU:"Custódio", data:"15/04", pe:"E", foto:"FOTOS/Custódio.jpeg", ao:"o"},
{nome:"Matheus Penteado", nomeU:"Matheus%20Penteado", data:"16/04", pe:"A", foto:"FOTOS/MatheusPenteado.jpeg", ao:"o"},
{nome:"Lucas Godoi", nomeU:"Lucas%20Godoi", data:"16/04", pe:"D", foto:"FOTOS/LucasGodoi.jpeg", ao:"o"},
{nome:"Vinícius Ramos", nomeU:"Vinícius%20Ramos", data:"17/04", pe:"A", foto:"FOTOS/ViníciusRamos.jpeg", ao:"o"},
{nome:"Lucas Resende", nomeU:"Lucas%20Resende", data:"17/04", pe:"F", foto:"FOTOS/LucasResende.jpeg", ao:"o"},
{nome:"Pinheiro", nomeU:"Pinheiro", data:"19/04", pe:"B", foto:"FOTOS/Pinheiro.jpeg", ao:"o"},
{nome:"Moreira", nomeU:"Moreira", data:"19/04", pe:"E", foto:"FOTOS/Moreira.jpeg", ao:"o"},
{nome:"L.Nogueira", nomeU:"L.Nogueira", data:"20/04", pe:"E", foto:"FOTOS/L.Nogueira.jpeg", ao:"o"},
{nome:"Teixeira", nomeU:"Teixeira", data:"21/04", pe:"E", foto:"FOTOS/Teixeira.jpeg", ao:"o"},
{nome:"Galetti", nomeU:"Galetti", data:"24/04", pe:"A", foto:"FOTOS/Galetti.jpeg", ao:"o"},
{nome:"Bracho", nomeU:"Bracho", data:"24/04", pe:"B", foto:"FOTOS/Bracho.jpeg", ao:"o"},
{nome:"Renan Andrade", nomeU:"Renan%20Andrade", data:"24/04", pe:"E", foto:"FOTOS/RenanAndrade.jpeg", ao:"o"},
{nome:"Rubira", nomeU:"Rubira", data:"28/04", pe:"A", foto:"FOTOS/Rubira.jpeg", ao:"o"},
{nome:"Sanches", nomeU:"Sanches", data:"05/05", pe:"E", foto:"FOTOS/Sanches.jpeg", ao:"o"},
{nome:"Pedro Nascimento", nomeU:"Pedro%20Nascimento", data:"11/05", pe:"C", foto:"FOTOS/PedroNascimento.jpg", ao:"o"},
{nome:"Martines", nomeU:"Martines", data:"12/05", pe:"E", foto:"FOTOS/Martines.jpeg", ao:"o"},
{nome:"Fabretti", nomeU:"Fabretti", data:"16/05", pe:"B", foto:"FOTOS/Fabretti.jpeg", ao:"o"},
{nome:"Gustavo Correia", nomeU:"Gustavo%20Correia", data:"16/05", pe:"C", foto:"FOTOS/GustavoCorreia.jpg", ao:"o"},
{nome:"Julia Guimarães", nomeU:"Julia%20Guimarães", data:"17/05", pe:"B", foto:"FOTOS/JuliaGuimarães.jpeg", ao:"o"},
{nome:"Caetano", nomeU:"Caetano", data:"18/05", pe:"A", foto:"FOTOS/Caetano.jpeg", ao:"o"},
{nome:"Sarti", nomeU:"Sarti", data:"20/05", pe:"D", foto:"FOTOS/Sarti.jpeg", ao:"o"},
{nome:"Lucas Oliveira", nomeU:"Lucas%20Oliveira", data:"21/05", pe:"E", foto:"FOTOS/LucasOliveira.jpeg", ao:"o"},
{nome:"Pedrosa", nomeU:"Pedrosa", data:"22/05", pe:"A", foto:"FOTOS/Pedrosa.jpeg", ao:"o"},
{nome:"Paulo Henrique", nomeU:"Paulo%20Henrique", data:"23/05", pe:"D", foto:"FOTOS/PauloHenrique.jpeg", ao:"o"},
{nome:"Gustavo Ferreira", nomeU:"Gustavo%20Ferreira", data:"24/05", pe:"B", foto:"FOTOS/GustavoFerreira.jpeg", ao:"o"},
{nome:"Ana Almeida", nomeU:"Ana%20Almeida", data:"26/05", pe:"D", foto:"FOTOS/AnaAlmeida.jpeg", ao:"o"},
{nome:"Pedro Fernandes", nomeU:"Pedro%20Fernandes", data:"26/05", pe:"E", foto:"FOTOS/PedroFernandes.jpeg", ao:"o"},
{nome:"Galindo", nomeU:"Galindo", data:"26/05", pe:"F", foto:"FOTOS/Galindo.jpeg", ao:"o"},
{nome:"Saulo", nomeU:"Saulo", data:"29/05", pe:"D", foto:"FOTOS/Saulo.jpeg", ao:"o"},
{nome:"Bruno", nomeU:"Bruno", data:"29/05", pe:"E", foto:"FOTOS/Bruno.jpeg", ao:"o"},
{nome:"Zuanon", nomeU:"Zuanon", data:"02/06", pe:"A", foto:"FOTOS/Zuanon.jpeg", ao:"o"},
{nome:"Gustavo Alves", nomeU:"Gustavo%20Alves", data:"03/06", pe:"A", foto:"FOTOS/GustavoAlves.jpeg", ao:"o"},
{nome:"Diogo Lima", nomeU:"Diogo%20Lima", data:"04/06", pe:"C", foto:"FOTOS/DiogoLima.jpg", ao:"o"},
{nome:"Gabriel Lopes", nomeU:"Gabriel%20Lopes", data:"10/06", pe:"B", foto:"FOTOS/GabrielLopes.jpeg", ao:"o"},
{nome:"Santos", nomeU:"Santos", data:"11/06", pe:"D", foto:"FOTOS/Santos.jpeg", ao:"o"},
{nome:"Eduarda Aguiar", nomeU:"Eduarda%20Aguiar", data:"13/06", pe:"E", foto:"FOTOS/EduardaAguiar.jpeg", ao:"o"},
{nome:"M. Henrique", nomeU:"M.%20Henrique", data:"17/06", pe:"B", foto:"FOTOS/M.Henrique.jpeg", ao:"o"},
{nome:"João Vieira", nomeU:"João%20Vieira", data:"18/06", pe:"F", foto:"FOTOS/JoãoVieira.jpeg", ao:"o"},
{nome:"Paiva", nomeU:"Paiva", data:"18/06", pe:"F", foto:"FOTOS/Paiva.jpeg", ao:"o"},
{nome:"Gustavo Lima", nomeU:"Gustavo%20Lima", data:"22/06", pe:"F", foto:"FOTOS/GustavoLima.jpeg", ao:"o"},
{nome:"Kevin Lima", nomeU:"Kevin%20Lima", data:"27/06", pe:"C", foto:"FOTOS/KevinLima.jpg", ao:"o"},
{nome:"Del Barrio", nomeU:"Del%20Barrio", data:"28/06", pe:"D", foto:"FOTOS/DelBarrio.jpeg", ao:"o"},
{nome:"Vitor", nomeU:"Vitor", data:"29/06", pe:"A", foto:"FOTOS/Vitor.jpeg", ao:"o"},
{nome:"Bálsamo", nomeU:"Bálsamo", data:"07/07", pe:"A", foto:"FOTOS/Bálsamo.jpeg", ao:"o"},
{nome:"Enzo Hideki Aota", nomeU:"Enzo%20Hideki%20Aota", data:"12/07", pe:"C", foto:"FOTOS/Hideki.jpg", ao:"o"},
{nome:"Moratori", nomeU:"Moratori", data:"12/07", pe:"F", foto:"FOTOS/Moratori.jpeg", ao:"o"},
{nome:"Ulisses Silveira", nomeU:"Ulisses%20Silveira", data:"13/07", pe:"D", foto:"FOTOS/Ulisses.jpeg", ao:"o"},
{nome:"Fernando Silva", nomeU:"Fernando%20Silva", data:"18/07", pe:"D", foto:"FOTOS/FernandoSilva.jpeg", ao:"o"},
{nome:"Monezi", nomeU:"Monezi", data:"22/07", pe:"D", foto:"FOTOS/Monezi.jpeg", ao:"o"},
{nome:"Leonardo Pereira", nomeU:"Leonardo%20Pereira", data:"22/07", pe:"E", foto:"FOTOS/LeonardoPereira.jpeg", ao:"o"},
{nome:"Suzano", nomeU:"Suzano", data:"23/07", pe:"C", foto:"FOTOS/Suzano.jpg", ao:"o"},
{nome:"Jordy", nomeU:"Jordy", data:"24/07", pe:"A", foto:"FOTOS/Jordy.jpeg", ao:"o"},
{nome:"Archanjo", nomeU:"Archanjo", data:"26/07", pe:"A", foto:"FOTOS/Archanjo.jpeg", ao:"o"},
{nome:"Pianta", nomeU:"Pianta", data:"26/07", pe:"B", foto:"FOTOS/Pianta.jpeg", ao:"o"},
{nome:"Gutierrez", nomeU:"Gutierrez", data:"28/07", pe:"A", foto:"FOTOS/Gutierrez.jpeg", ao:"o"},
{nome:"Gabriel Sales", nomeU:"Gabriel%20Sales", data:"29/07", pe:"A", foto:"FOTOS/GabrielSales.jpeg", ao:"o"},
{nome:"Kobayashi", nomeU:"Kobayashi", data:"31/07", pe:"E", foto:"FOTOS/Kobayashi.jpeg", ao:"o"},
{nome:"Arthur Leal", nomeU:"Arthur%20Leal", data:"02/08", pe:"A", foto:"FOTOS/ArthurLeal.jpeg", ao:"o"},
{nome:"Camila", nomeU:"Camila", data:"07/08", pe:"D", foto:"FOTOS/Camila.jpeg", ao:"o"},
{nome:"Madeira", nomeU:"Madeira", data:"09/08", pe:"A", foto:"FOTOS/Madeira.jpeg", ao:"o"},
{nome:"De Proença", nomeU:"De%20Proença", data:"16/08", pe:"E", foto:"FOTOS/DeProença.jpeg", ao:"o"},
{nome:"Calzavara", nomeU:"Calzavara", data:"19/08", pe:"E", foto:"FOTOS/Calzavara.jpeg", ao:"o"},
{nome:"Leal", nomeU:"Leal", data:"21/08", pe:"A", foto:"FOTOS/Leal.jpeg", ao:"o"},
{nome:"Koga", nomeU:"Koga", data:"23/08", pe:"F", foto:"FOTOS/Koga.jpeg", ao:"o"},
{nome:"Davi Rocha", nomeU:"Davi%20Rocha", data:"24/08", pe:"C", foto:"FOTOS/DaviRocha.jpg", ao:"o"},
{nome:"Pedro Delfino", nomeU:"Pedro%20Delfino", data:"27/08", pe:"E", foto:"FOTOS/PedroDelfino.jpeg", ao:"o"},
{nome:"Andressa", nomeU:"Andressa", data:"02/09", pe:"F", foto:"FOTOS/Andressa.jpeg", ao:"o"},
{nome:"Demarchi", nomeU:"Demarchi", data:"03/09", pe:"B", foto:"FOTOS/Demarchi.jpeg", ao:"o"},
{nome:"Galdini", nomeU:"Galdini", data:"03/09", pe:"B", foto:"FOTOS/Galdini.jpeg", ao:"o"},
{nome:"Melhado", nomeU:"Melhado", data:"04/09", pe:"F", foto:"FOTOS/Melhado.jpeg", ao:"o"},
{nome:"Foltran", nomeU:"Foltran", data:"11/09", pe:"B", foto:"FOTOS/Foltran.jpeg", ao:"o"},
{nome:"Hackenbracht", nomeU:"Hackenbracht", data:"11/09", pe:"C", foto:"FOTOS/Hackenbratch.jpg", ao:"o"},
{nome:"Julliana Miranda", nomeU:"Julliana%20Miranda", data:"11/09", pe:"C", foto:"FOTOS/JullianaMiranda.jpg", ao:"o"},
{nome:"De Carvalho", nomeU:"De%20Carvalho", data:"13/09", pe:"B", foto:"FOTOS/DeCarvalho.jpeg", ao:"o"},
{nome:"Gabriel", nomeU:"Gabriel", data:"13/09", pe:"B", foto:"FOTOS/Gabriel.jpeg", ao:"o"},
{nome:"Vinicius Almeida", nomeU:"Vinicius%20Almeida", data:"18/09", pe:"D", foto:"FOTOS/ViniciusAlmeida.jpeg", ao:"o"},
{nome:"Zambon", nomeU:"Zambon", data:"22/09", pe:"A", foto:"FOTOS/Zambon.jpeg", ao:"o"},
{nome:"Letícia Arantes", nomeU:"Letícia%20Arantes", data:"23/09", pe:"F", foto:"FOTOS/LetíciaArantes.jpeg", ao:"o"},
{nome:"M. Vianna", nomeU:"M.%20Vianna", data:"24/09", pe:"B", foto:"FOTOS/M.Vianna.jpeg", ao:"o"},
{nome:"Ravely", nomeU:"Ravely", data:"24/09", pe:"D", foto:"FOTOS/Ravely.jpeg", ao:"o"},
{nome:"Luiz Martins", nomeU:"Luiz%20Martins", data:"05/10", pe:"E", foto:"FOTOS/LuizMartins.jpeg", ao:"o"},
{nome:"Rocia", nomeU:"Rocia", data:"06/10", pe:"F", foto:"FOTOS/Rocia.jpeg", ao:"o"},
{nome:"Baltar", nomeU:"Baltar", data:"09/10", pe:"B", foto:"FOTOS/Baltar.jpeg", ao:"o"},
{nome:"Cavicchioli", nomeU:"Cavicchioli", data:"11/10", pe:"C", foto:"FOTOS/Cavicchioli.jpg", ao:"o"},
{nome:"Alcantara", nomeU:"Alcantara", data:"21/10", pe:"C", foto:"FOTOS/Alcântara.jpg", ao:"o"},
{nome:"Gustavo Suedik", nomeU:"Gustavo%20Suedik", data:"21/10", pe:"F", foto:"FOTOS/GustavoSuedik.jpeg", ao:"o"},
{nome:"Aquilar", nomeU:"Aquilar", data:"23/10", pe:"A", foto:"FOTOS/Aquilar.jpeg", ao:"o"},
{nome:"Homero", nomeU:"Homero", data:"28/10", pe:"B", foto:"FOTOS/Homero.jpeg", ao:"o"},
{nome:"Alex Marques", nomeU:"Alex%20Marques", data:"31/10", pe:"F", foto:"FOTOS/AlexMarques.jpeg", ao:"o"},
{nome:"Carla Gil", nomeU:"Carla%20Gil", data:"01/11", pe:"C", foto:"FOTOS/CarlaGil.jpg", ao:"o"},
{nome:"Da Cruz", nomeU:"Da%20Cruz", data:"03/11", pe:"D", foto:"FOTOS/DaCruz.jpeg", ao:"o"},
{nome:"Andreoni", nomeU:"Andreoni", data:"03/11", pe:"E", foto:"FOTOS/Andreoni.jpeg", ao:"o"},
{nome:"Helen", nomeU:"Helen", data:"04/11", pe:"D", foto:"FOTOS/Helen.jpeg", ao:"o"},
{nome:"Toldato", nomeU:"Toldato", data:"10/11", pe:"E", foto:"FOTOS/Toldato.jpeg", ao:"o"},
{nome:"Pasquini", nomeU:"Pasquini", data:"11/11", pe:"C", foto:"FOTOS/Pasquini.jpg", ao:"o"},
{nome:"Reis", nomeU:"Reis", data:"13/11", pe:"C", foto:"FOTOS/Reis.jpg", ao:"o"},
{nome:"Adriano Couto", nomeU:"Adriano%20Couto", data:"17/11", pe:"B", foto:"FOTOS/AdrianoCouto.jpeg", ao:"o"},
{nome:"Pedro Alves", nomeU:"Pedro%20Alves", data:"18/11", pe:"D", foto:"FOTOS/Pedro.jpeg", ao:"o"},
{nome:"Origa", nomeU:"Origa", data:"20/11", pe:"E", foto:"FOTOS/Origa.jpeg", ao:"o"},
{nome:"Chiodi", nomeU:"Chiodi", data:"25/11", pe:"F", foto:"FOTOS/Chiodi.jpeg", ao:"o"},
{nome:"Larissa Minhão", nomeU:"Larissa%20Minhão", data:"29/11", pe:"A", foto:"FOTOS/LarissaMinhão.jpeg", ao:"o"},
{nome:"Naressi", nomeU:"Naressi", data:"02/12", pe:"E", foto:"FOTOS/Naressi.jpeg", ao:"o"},
{nome:"Villas Boas", nomeU:"Villas%20Boas", data:"03/12", pe:"A", foto:"FOTOS/VillasBoas.jpeg", ao:"o"},
{nome:"Henrique Fortes", nomeU:"Henrique%20Fortes", data:"05/12", pe:"D", foto:"FOTOS/HenriqueFortes.jpeg", ao:"o"},
{nome:"Eckel Rangel", nomeU:"Eckel%20Rangel", data:"06/12", pe:"C", foto:"FOTOS/EckelRangel.jpg", ao:"o"},
{nome:"Della Garza", nomeU:"Della%20Garza", data:"06/12", pe:"D", foto:"FOTOS/DellaGarza.jpeg", ao:"o"},
{nome:"Fisher", nomeU:"Fisher", data:"07/12", pe:"C", foto:"FOTOS/Fisher.jpg", ao:"o"},
{nome:"Ricardo Souza", nomeU:"Ricardo%20Souza", data:"07/12", pe:"F", foto:"FOTOS/RicardoSouza.jpeg", ao:"o"},
{nome:"Sandy", nomeU:"Sandy", data:"09/12", pe:"B", foto:"FOTOS/Sandy.jpeg", ao:"o"},
{nome:"Pina", nomeU:"Pina", data:"10/12", pe:"C", foto:"FOTOS/Pina.jpg", ao:"o"},
{nome:"Anderson Luiz", nomeU:"Anderson%20Luiz", data:"10/12", pe:"E", foto:"FOTOS/AndersonLuiz.jpeg", ao:"o"},
{nome:"Urbanjos", nomeU:"Urbanjos", data:"13/12", pe:"C", foto:"FOTOS/Urbanjos.jpg", ao:"o"},
{nome:"Victor Gama", nomeU:"Victor%20Gama", data:"14/12", pe:"A", foto:"FOTOS/VictorGama.jpeg", ao:"o"},
{nome:"Canhameiro", nomeU:"Canhameiro", data:"14/12", pe:"F", foto:"FOTOS/Canhameiro.jpeg", ao:"o"},
{nome:"Campos", nomeU:"Campos", data:"15/12", pe:"E", foto:"FOTOS/Campos.jpeg", ao:"o"},
{nome:"Hubner", nomeU:"Hubner", data:"16/12", pe:"B", foto:"FOTOS/Hubner.jpeg", ao:"o"},
{nome:"Nícollas Arruda", nomeU:"Nícollas%20Arruda", data:"18/12", pe:"E", foto:"FOTOS/NícollasArruda.jpeg", ao:"o"},
{nome:"Marcos Junior", nomeU:"Marcos%20Junior", data:"21/12", pe:"F", foto:"FOTOS/MarcosJunior.jpeg", ao:"o"},
{nome:"Spilla", nomeU:"Spilla", data:"24/12", pe:"A", foto:"FOTOS/Spilla.jpeg", ao:"o"},
{nome:"Marcilio", nomeU:"Marcilio", data:"27/12", pe:"D", foto:"FOTOS/Marcilio.jpeg", ao:"o"},
{nome:"Renan Ferreira", nomeU:"Renan%20Ferreira", data:"29/12", pe:"B", foto:"FOTOS/RenanFerreira.jpeg", ao:"o"},
{nome:"Rafael Lira", nomeU:"Rafael%20Lira", data:"29/12", pe:"D", foto:"FOTOS/RafaelLira.jpeg", ao:"o"},
{nome:"Klaus", nomeU:"Klaus", data:"29/12", pe:"C", foto:"FOTOS/Klaus.jpg", ao:"o"},
{nome:"Kaue Tobias", nomeU:"Kaue%20Tobias", data:"31/12", pe:"C", foto:"FOTOS/KaueTobias.jpg", ao:"o"}
]

